Use "/var/log/delphix-upgrade" for upgrade logs
This change modifies the upgrade logic to use a new directory for
storing upgrade log files. This directory is contained on the host's
root filesystem, but is bind mounted into the container. This way,
software running in the upgrade container can write to it, and the files
can be accessed by software running on the host.

diff --git a/live-build/misc/upgrade-scripts/verify-impl b/live-build/misc/upgrade-scripts/verify-impl
--- a/live-build/misc/upgrade-scripts/verify-impl
+++ b/live-build/misc/upgrade-scripts/verify-impl
@@ -17,17 +17,8 @@
 
 . "${BASH_SOURCE%/*}/common.sh"
 
-IMAGE_PATH=$(get_image_path)
-[[ -n "$IMAGE_PATH" ]] || die "failed to determine image path"
-
 IMAGE_VERSION=$(get_image_version)
 [[ -n "$IMAGE_VERSION" ]] || die "failed to determine image version"
-
-UPDATE_DIR="$(dirname "$IMAGE_PATH")"
-[[ -n "$UPDATE_DIR" ]] || die "failed to determine update directory"
-
-LOG_DIR="${UPDATE_DIR}/verify-logs"
-LOG_SCRIPT="/opt/delphix/server/bin/support_info"
 
 function usage() {
 	echo "$(basename "$0"): $*" >&2
@@ -35,11 +26,12 @@ function usage() {
 	exit 2
 }
 
-function run_support_info_script() {
+function run_support_info() {
 	local rc="$?"
 
-	"${LOG_SCRIPT}" -o "${LOG_DIR}/${CONTAINER}" -t "log dropbox" ||
-		die "Failed to collect verify logs."
+	/opt/delphix/server/bin/support_info \
+		-o "${LOG_DIRECTORY}/${CONTAINER}" \
+		-t "log dropbox" || die "Failed to collect verify logs."
 
 	return "$rc"
 }
@@ -69,24 +61,17 @@ fi
 # the host. This allows the software running on the host to easily
 # access the logs after the verification is performed.
 #
-# Additionally, we only want to save the logs for one verification
-# invocation at any given time; mostly to avoid these logs from
-# consuming storage unnecessarily. Thus, we delete the existing
-# directory first, and then recreate an empty directory.
-#
-rm -rf "${LOG_DIR:?}" ||
-	die "failed to remove directory: '${LOG_DIR}'"
-mkdir -p "${LOG_DIR}/${CONTAINER}" ||
-	die "failed to create directory: '${LOG_DIR}/${CONTAINER}'"
+mkdir -p "${LOG_DIRECTORY}/${CONTAINER}" ||
+	die "failed to create directory: '${LOG_DIRECTORY}/${CONTAINER}'"
 
-trap run_support_info_script EXIT
+trap run_support_info EXIT
 
 /usr/bin/java \
 	-Dlog.dir=/var/delphix/server/upgrade-verify \
 	-Dmdsverify=true \
 	$VERIFY_DEBUG_OPT \
 	-jar /opt/delphix/server/lib/exec/upgrade-verify/upgrade-verify.jar \
-	-d "${opt_o:-${LOG_DIR}/${CONTAINER}/upgrade_verify_report.json}" \
+	-d "${opt_o:-${LOG_DIRECTORY}/${CONTAINER}/upgrade_verify.json}" \
 	-f "${opt_f:-1}" \
 	-l "${opt_l:-en-US}" \
 	-v "$IMAGE_VERSION" \
