LX-1418 Add mechanism to save container logs to a host

diff --git a/live-build/misc/upgrade-scripts/verify-impl b/live-build/misc/upgrade-scripts/verify-impl
--- a/live-build/misc/upgrade-scripts/verify-impl
+++ b/live-build/misc/upgrade-scripts/verify-impl
@@ -26,6 +26,24 @@ function usage() {
 	exit 2
 }
 
+function cleanup() {
+	local rc="$?"
+
+	#
+	# Persist container logs by saving to the container's host.
+	# Delete and create verify log destination directory to save only one copy of log to limit
+	# space usage.
+	#
+	rm -rf "${UPDATE_VERIFY_LOG_DIR:?}" ||
+		die "Failed to remove verify log directory ${UPDATE_VERIFY_LOG_DIR}."
+	mkdir -p "${UPDATE_VERIFY_LOG_DIR}/${CONTAINER}" ||
+		die "Failed to create verify log directory ${UPDATE_VERIFY_LOG_DIR}/${CONTAINER}."
+	${SUPPORT_INFO_SCRIPT} -o "${UPDATE_VERIFY_LOG_DIR}/${CONTAINER}" -t "log dropbox" ||
+		die "Failed to collect verify logs."
+
+	return "$rc"
+}
+
 opt_d=false
 while getopts ':df:l:o:' c; do
 	case "$c" in
@@ -44,6 +62,8 @@ fi
 if $opt_d; then
 	VERIFY_LIVE_MDS_OPT="-disableConsistentMdsZfsDataUtil"
 fi
+
+trap cleanup EXIT
 
 /usr/bin/java \
 	-Dlog.dir=/var/delphix/server/upgrade-verify \
