Add "upgrade" script that can upgrade an appliance
This change adds a new "upgrade" script to the set of upgrade-scripts.
This new script is intended to be used to upgrade an existing appliance
to the version contained in the upgrade image; the script supports both,
"in-place" and "not-in-place" upgrades.

diff --git a/live-build/misc/upgrade-scripts/verify b/live-build/misc/upgrade-scripts/verify
--- a/live-build/misc/upgrade-scripts/verify
+++ b/live-build/misc/upgrade-scripts/verify
@@ -20,16 +20,9 @@
 IMAGE_PATH=$(get_image_path)
 [[ -n "$IMAGE_PATH" ]] || die "failed to determine image path"
 
-IMAGE_VERSION=$(get_image_version)
-[[ -n "$IMAGE_VERSION" ]] || die "failed to determine image version"
+[[ "$EUID" -ne 0 ]] && die "must be run as root"
 
-function usage() {
-	echo "$(basename "$0"): $*" >&2
-	echo "Usage: $(basename "$0") -v <version>"
-	exit 2
-}
-
-function report_progress_inc() {
+function report_progress() {
 	echo "Progress increment: $(date +%T:%N%z), $1, $2"
 }
 
@@ -48,94 +41,46 @@ function cleanup() {
 	#
 	[[ -z "$CONTAINER" ]] && return
 
-	#
-	# On failure, and when DLPX_DEBUG is true, we avoid cleaning up
-	# the verification container. This is intended to make it easier
-	# to diagnose and debug verification failures on developer
-	# machines.
-	#
-	if [[ $rc -ne 0 ]] && [[ -n "$DLPX_DEBUG" ]] && $DLPX_DEBUG; then
-		report_progress_inc 80 "Skipping upgrade verification cleanup"
-	else
-		report_progress_inc 80 "Performing upgrade verification cleanup"
+	if [[ "$rc" == "0" || "$DLPX_DEBUG" != "true" ]]; then
+		report_progress 80 "Performing upgrade verification cleanup"
 
-		"$IMAGE_PATH/upgrade-container" stop "$CONTAINER"
-		"$IMAGE_PATH/upgrade-container" destroy "$CONTAINER"
+		#
+		# On success, or on failure when DLPX_DEBUG is not true,
+		# we clean up the container previously created. When
+		# DLPX_DEBUG is true, we leave the container around on
+		# failure to aid debugging efforts.
+		#
+		"$IMAGE_PATH/upgrade-container" stop "$CONTAINER" ||
+			warn "failed to stop container '$CONTAINER'"
+		"$IMAGE_PATH/upgrade-container" destroy "$CONTAINER" ||
+			warn "failed to stop container '$CONTAINER'"
+	else
+		report_progress 80 "Skipping upgrade verification cleanup"
 	fi
 
-	[[ $rc -eq 0 ]] &&
-		report_progress_inc 100 "Upgrade verification was successful"
+	return "$rc"
 }
-
-opt_d=false
-while getopts ':df:l:o:' c; do
-	case "$c" in
-	f | l | o) eval "opt_$c=$OPTARG" ;;
-	d) eval "opt_$c=true" ;;
-	*) usage "illegal option -- $OPTARG" ;;
-	esac
-done
-
-[[ "$EUID" -ne 0 ]] && die "must be run as root"
 
 trap cleanup EXIT
 
-report_progress_inc 0 "Creating upgrade verification container"
-
+report_progress 0 "Creating upgrade verification container"
 CONTAINER=$("$IMAGE_PATH/upgrade-container" create in-place)
-[[ -n "$CONTAINER" ]] || die "failed to create verify container"
+[[ -n "$CONTAINER" ]] || die "failed to create container"
 
-report_progress_inc 20 "Starting upgrade verification container"
-
+report_progress 20 "Starting upgrade verification container"
 "$IMAGE_PATH/upgrade-container" start "$CONTAINER" ||
-	die "failed to start verify container '$CONTAINER'"
+	die "failed to start '$CONTAINER'"
 
-report_progress_inc 40 "Performing package upgrade verification"
-
+report_progress 40 "Performing package upgrade verification"
 "$IMAGE_PATH/upgrade-container" run "$CONTAINER" "$IMAGE_PATH/execute" ||
-	die "'$IMAGE_PATH/execute' failed in verification container"
+	die "'$IMAGE_PATH/execute' failed in '$CONTAINER'"
 
-report_progress_inc 60 "Performing application upgrade verification"
-
-if [[ -n "$DLPX_DEBUG" ]] && $DLPX_DEBUG; then
-	VERIFY_DEBUG_OPT="-Ddelphix.debug=true"
-fi
-
-if $opt_d; then
-	VERIFY_LIVE_MDS_OPT="-disableConsistentMdsZfsDataUtil"
-fi
-
+report_progress 60 "Performing application upgrade verification"
 "$IMAGE_PATH/upgrade-container" run "$CONTAINER" \
-	/usr/bin/java \
-	-Dlog.dir=/var/delphix/server/upgrade-verify \
-	-Dmdsverify=true \
-	$VERIFY_DEBUG_OPT \
-	-jar /opt/delphix/server/lib/exec/upgrade-verify/upgrade-verify.jar \
-	-d "${opt_o:-$DROPBOX_DIR/upgrade_verify_report.json}" \
-	-f "${opt_f:-1}" \
-	-l "${opt_l:-en-US}" \
-	-v "$IMAGE_VERSION" \
-	-pl 60 -ph 80 \
-	$VERIFY_LIVE_MDS_OPT ||
-	die "'upgrade-verify.jar' failed in verification container"
-
-#
-# This name is used by the "upgrade-verify.jar" just executed, so we
-# cannot change this value without also modifying that JAR.
-#
-MDS_SNAPNAME="MDS-CLONE-upgradeverify"
-
-"$IMAGE_PATH/upgrade-container" run "$CONTAINER" \
-	/opt/delphix/server/bin/dx_manage_pg stop -s "$MDS_SNAPNAME" ||
-	die "failed to stop postgres"
-
-"$IMAGE_PATH/upgrade-container" run "$CONTAINER" \
-	/opt/delphix/server/bin/dx_manage_pg cleanup -s "$MDS_SNAPNAME" ||
-	die "failed to cleanup postgres"
+	"$IMAGE_PATH/verify-impl" "$@" ||
+	die "'$IMAGE_PATH/verify-impl' '$*' failed in '$CONTAINER'"
 
 #
 # The cleanup logic will be run on EXIT, so rather than reporting 100
 # percent here, we use the cleanup logic to do the final reporting.
 #
-
-exit 0
