fixup: attempt to derive list of packages dynamically

diff --git a/upgrade/upgrade-scripts/execute b/upgrade/upgrade-scripts/execute
--- a/upgrade/upgrade-scripts/execute
+++ b/upgrade/upgrade-scripts/execute
@@ -350,22 +350,12 @@ zcat "/usr/share/doc/delphix-entire-$platform/packages.list.gz" |
 # First, since "apt-get autoremove" does not work properly for the
 # kernel packages, we have to handle the removal of those here.
 #
-KVERS=$(apt-mark showauto 'delphix-kernel-.*' | sed 's/^delphix-kernel-//') ||
-	die "failed to determine list of kernel versions to remove"
-for KVER in $KVERS; do
-	apt_get purge -y \
-		"delphix-kernel-$KVER" \
-		"linux-image-$KVER" \
-		"linux-image-$KVER-dbgsym" \
-		"linux-modules-extra-$KVER" \
-		"linux-headers-$KVER" \
-		"linux-tools-$KVER" \
-		"zfs-modules-$KVER" \
-		"zfs-modules-$KVER-dbg" \
-		"zfs-headers-$KVER" \
-		"connstat-module-$KVER" ||
-		die "failed to remove kernel packages for version '$KVER'"
-done
+apt-mark showauto 'delphix-kernel-.*' | while read -r pkg; do
+	# shellcheck disable=SC2046
+	apt_get purge -y "$pkg" \
+		$(dpkg-query -Wf '${Depends}' "$pkg" | sed 's/, / /g') ||
+		die "failed to remove delphix-kernel packages: '$pkg'"
+done || die "failed to remove delphix-kernel and dependent packages"
 
 #
 # Next, APT will automatically try to prevent kernel packages from being
