DLPX-94067 LTS 24.04: update appliance-build for Ubuntu 24.04 appliance
PR URL: https://www.github.com/delphix/appliance-build/pull/812

diff --git a/upgrade/upgrade-scripts/execute b/upgrade/upgrade-scripts/execute
--- a/upgrade/upgrade-scripts/execute
+++ b/upgrade/upgrade-scripts/execute
@@ -200,7 +200,7 @@ rm -f /etc/apt/sources.list.d/*
 # image.
 #
 cat <<EOF >/etc/apt/sources.list ||
-deb [trusted=yes] file://$IMAGE_PATH focal delphix
+deb [trusted=yes] file://$IMAGE_PATH noble delphix
 EOF
 	die "failed to configure apt sources"
 
@@ -258,6 +258,19 @@ dpkg --configure -a || die "failed to run dpkg --configure -a"
 	sed -i '/\/var\/lib\/nfs\/rmtab/d' /var/lib/dpkg/info/nfs-kernel-server.list
 
 apt_get update || die "failed to update apt sources"
+
+#
+# If the version of systemd changes enough during an upgrade, it's possible
+# for various systemd commands (e.g. systemctl disable) to fail, as the running
+# version of systemd might not match what the new packages expect. We've had
+# this happen when upgrading LTS versions. If those commands fail as part of
+# a package hook, that can cause the upgrade to as a whole to fail.
+#
+# Thus, to try and prevent this, we first upgrade the systemd package, and
+# restart the systemd process, before moving on to upgrading any other packages.
+#
+apt_get install -y "systemd" || die "failed to install systemd"
+systemctl daemon-reexec || die "'systemctl daemon-reexec' failed"
 
 #
 # Currently, we need to run the delphix-platform's "postinst" packaging hook
@@ -384,6 +397,21 @@ zcat "/usr/share/doc/delphix-entire-$opt_p/packages.list.gz" |
 	die "failed to mark as manual packages listed in packages.list.gz file"
 
 #
+# As part of the LTS upgrade project to 24.04, `ntp` was replaced by `ntpsec`.
+# To preserve and migrate the NTP configuration, we need to copy the
+# NTP configuration file to the new location after packages are upgraded,
+# but before they are removed so that NTP continues to function as expected.
+#
+if [[ -f "/etc/ntp/ntp.conf" ]]; then
+	cp /etc/ntp/ntp.conf /etc/ntpsec/ntp.conf ||
+		die "failed to copy /etc/ntp/ntp.conf to /etc/ntpsec/ntp.conf"
+	if [[ "$(systemctl is-enabled ntp.service)" == enabled ]]; then
+		systemctl disable --now ntp.service
+		systemctl enable ntpsec.service
+	fi
+fi
+
+#
 # After we've successfully installed the new packages and marked them
 # all as manual-ly installed, we need to remove all packages that are no
 # longer required. For example, if the old "delphix-entire" version
@@ -484,6 +512,15 @@ rm -f /etc/apt/sources.list.d/*
 #
 if [[ "$(systemctl is-enabled telegraf)" == enabled ]]; then
 	systemctl mask --now telegraf.service
+fi
+
+#
+# Upgrading to LTS 24.04 causes the `ntpsec` package to be installed. This package installs the
+# `ntpsec-rotate-stats.timer` timer which is enabled by default. Our product never enables
+# the collection of NTP stats, so we disable the timer to prevent it from running.
+#
+if [[ "$(systemctl is-enabled ntpsec-rotate-stats.timer)" == enabled ]]; then
+	systemctl mask --now ntpsec-rotate-stats.timer
 fi
 
 #
