DLPX-75209 -- Fix for upgrade scenario

diff --git a/upgrade/upgrade-scripts/execute b/upgrade/upgrade-scripts/execute
--- a/upgrade/upgrade-scripts/execute
+++ b/upgrade/upgrade-scripts/execute
@@ -17,6 +17,8 @@
 
 . "${BASH_SOURCE%/*}/common.sh"
 
+INTERFACE_TO_MACADRESS_MAP_FILE_PATH="/etc/interface_to_macaddress_map.out"
+
 IMAGE_PATH=$(get_image_path)
 [[ -n "$IMAGE_PATH" ]] || die "failed to determine image path"
 
@@ -26,6 +28,25 @@ function usage() {
 	echo "$(basename "$0"): $*" >&2
 	echo "Usage: $(basename "$0") -p <platform>"
 	exit 2
+}
+
+function generate_interface_to_mac_address_map() {
+  # we always create the map file anew to avoid using any stale versions of the same
+  if [[ -e "$INTERFACE_TO_MACADRESS_MAP_FILE_PATH" ]]; then
+    > "$INTERFACE_TO_MACADRESS_MAP_FILE_PATH" || \
+      die "Could not delete the existing contents of the mac address map file"
+  fi
+  for i in $(ls -lart /sys/class/net | awk '{print $9}');
+  do
+    interface_name="$i";
+    if [ -e /sys/class/net/"$i"/address ] && \
+      grep -q -v -e "00:00:00:00:00:00" /sys/class/net/$i/address ; then
+      mac_address=$(cat /sys/class/net/"$i"/address | tr -d ":");
+      echo $interface_name $mac_address >> "$INTERFACE_TO_MACADRESS_MAP_FILE_PATH"
+    fi;
+  done
+  [ -s "$INTERFACE_TO_MACADRESS_MAP_FILE_PATH" ] || \
+    die "Failed to generate map from interface names to mac addresses"
 }
 
 while getopts ':rlBfsp:' c; do
@@ -457,6 +478,42 @@ else
 	zfs inherit "$PROP_HOTFIX_VERSION" "$ROOTFS_CONTAINER" ||
 		die "failed to inherit property '$PROP_HOTFIX_VERSION'" \
 			"for '$ROOTFS_CONTAINER'"
+fi
+
+# In AWS environments, changing instance type could result in generation of
+# different network interface names compared to the existing ones. This mismatch
+# causes our netplan file handler in the osadmin service to remove the existing
+# entries in the netplan plan, because they are not to be found on the new instance.
+# However, the mac address remains consistent and does not change with a change in
+# the instance types.
+# To handle this, from 6.0.16.0 onwards, we are switching to use mac address based
+# interface names in the netplan file. To facilitate this change across upgrades from
+# older verrsions to 6.0.16.0 and above, we create a map from the network interface
+# names to their corresponding mac address, resulting in mac addrress based interface
+# names. For wider context, see DLPX-75209.
+#
+# For deferred upgrades, we cannot know when the engine will be rebooted into the new
+# image. The decision depends on the end-user. Hence we always create the map file
+# irrespective of the upgrade type, to allow the upgrade finalize logic to copy the
+# map file from the currently mounted root filesystem to the root filesystem of the
+# target container.
+#
+# The map creation logic does not apply to engines being upgraded from 6.0.16.0 onwards.
+# This is because the netplan file from 6.0.16.0 will by default be populated with mac
+# address based interface names. This makes this logic redundant for upgrades from
+# 6.0.16.0 and onwards. Hence, we must remove this logic as soon as we mark 6.0.16.0 as
+# the minimum version supported release.
+
+# The container does not have visibility into the complete network namespace of the
+# engine. Hence we need to create the map outside the container to ensure the presense
+# of all the interfaces in the map
+if ! systemd-detect-virt --container --quiet && [[ $(get-appliance-platform) == "aws" ]]; then
+  # While booting back to the original image post rollback, we want to reuse the original
+  # netplan file that consisted of the canonical interface names generated by the kernel.
+  # Hence, we skip creating the map file in rollback execution path
+  if [[ "$1" != "rollback" ]]; then
+    generate_interface_to_mac_address_map
+  fi
 fi
 
 #
