DLPX-69447 Fixed hotfixes should be removed from /etc/hotfix during upgrade application (#482)

diff --git a/upgrade/upgrade-scripts/upgrade b/upgrade/upgrade-scripts/upgrade
--- a/upgrade/upgrade-scripts/upgrade
+++ b/upgrade/upgrade-scripts/upgrade
@@ -446,6 +446,10 @@ function finalize() {
 	rm -rf "$IMAGE_PATH" || die "failed to remove unpacked upgrade image"
 
 	remove_upgrade_properties
+
+	if [[ -f "$HOTFIX_PATH" ]]; then
+		rm -f "$HOTFIX_PATH" || die "failed to remove hotfix file"
+	fi
 }
 
 [[ "$EUID" -ne 0 ]] && die "must be run as root"
