DLPX-86523 CIS: /home filesystem and mount options
PR URL: https://www.github.com/delphix/appliance-build/pull/756

diff --git a/upgrade/upgrade-scripts/upgrade-container b/upgrade/upgrade-scripts/upgrade-container
--- a/upgrade/upgrade-scripts/upgrade-container
+++ b/upgrade/upgrade-scripts/upgrade-container
@@ -177,7 +177,7 @@ function create_upgrade_container() {
 		-o mountpoint=legacy \
 		"$ROOTFS_DATASET/home@$SNAPSHOT_NAME" \
 		"rpool/ROOT/$CONTAINER/home" ||
-		die "failed to create upgrade /export/home clone"
+		die "failed to create upgrade /home clone"
 
 	zfs clone \
 		-o mountpoint=legacy \
@@ -205,6 +205,90 @@ function create_upgrade_container() {
 			die "failed to create upgrade /var/tmp clone"
 	fi
 
+	case "$type" in
+	not-in-place)
+		#
+		# We need to ensure all of the upgrade container's datasets
+		# are mounted before running "debootstrap". This way, if any
+		# packages installed by "debootstrap" happen to deliver
+		# files to any of these directories, they'll be propertly
+		# delivered to the correct dataset, rather than the root
+		# dataset.
+		#
+		mount_upgrade_container_dataset \
+			"rpool/ROOT/$CONTAINER/home" "$DIRECTORY/home"
+		mount_upgrade_container_dataset \
+			"rpool/ROOT/$CONTAINER/data" "$DIRECTORY/var/delphix"
+		mount_upgrade_container_dataset \
+			"rpool/ROOT/$CONTAINER/log" "$DIRECTORY/var/log"
+
+		if $TMP_DATASETS_EXIST; then
+			mount_upgrade_container_dataset \
+				"rpool/ROOT/$CONTAINER/tmp" "$DIRECTORY/tmp"
+			mount_upgrade_container_dataset \
+				"rpool/ROOT/$CONTAINER/vartmp" "$DIRECTORY/var/tmp"
+		fi
+
+		#
+		# This function needs to return the container's name to
+		# stdout, so that consumers of this function/script can
+		# consume that name and then later start/stop/destroy the
+		# container. Thus, we have to redirect the output from
+		# debootstrap away from stdout.
+		#
+		# Also, we need to include the "systemd-container" package
+		# when installing the base systemd with debootstrap so that
+		# starting the container will work properly. Otherwise,
+		# after starting the container, we won't be able to
+		# communicate and later run commands in the container with
+		# "systemd-run".
+		#
+		# On Ubuntu 20.04, in-order to satisfy some package
+		# dependencies, we must set the variant to "minbase" and list
+		# "ntp" in the include list before "systemd-container".
+		# Setting the variant to minbase removes systemd from the
+		# packages being installed by default. Systemd will still
+		# be installed, but in a later pass, as a dependency of
+		# systemd-container. The reason we need to go through those
+		# hoops is the following:
+		#  - systemd has a package dependency on a "time-daemon"
+		#    virtual package, which is provided by either "ntp" or
+		#    "systemd-timesyncd".
+		#  - If a time-deamon is not already installed when
+		#    installing systemd, then systemd will try to
+		#    install systemd-timesyncd.
+		#  - systemd-timesyncd is not available in our upgrade
+		#    images because we install ntp and ntp conflicts with
+		#    systemd-timesyncd.
+		#  - Setting variant as minbase and list ntp before
+		#    systemd-container in the include list allows debootstrap
+		#    to install ntp before systemd, thus satisfying the
+		#    package dependencies.
+		# Note that we do not run into those problems during live-build
+		# because debootstrap is already run with variant=minbase and
+		# systemd is not installed by debootstrap, but rather by
+		# delphix-platform which pulls both ntp and systemd.
+		#
+		debootstrap --no-check-gpg --variant=minbase \
+			--components=delphix --include=ntp,systemd-container \
+			focal "$DIRECTORY" "file://$IMAGE_PATH" 1>&2 ||
+			die "failed to debootstrap upgrade filesystem"
+
+		#
+		# Now that we've successfully run "deboostrap", we can
+		# unmount these datasets that were mounted above.
+		#
+		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/log"
+		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/data"
+		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/home"
+
+		if $TMP_DATASETS_EXIST; then
+			unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/tmp"
+			unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/vartmp"
+		fi
+		;;
+	esac
+
 	#
 	# We rely on the "/etc/fstab" file to mount the non-root ZFS
 	# filesystems, so that when a specific rootfs dataset is booted,
@@ -213,7 +297,7 @@ function create_upgrade_container() {
 	# before the zfs-import service is run.
 	#
 	cat <<-EOF >"$DIRECTORY/etc/fstab"
-		rpool/ROOT/$CONTAINER/home /export/home zfs defaults,x-systemd.before=zfs-import-cache.service 0 0
+		rpool/ROOT/$CONTAINER/home /home zfs defaults,nodev,x-systemd.before=zfs-import-cache.service 0 0
 		rpool/ROOT/$CONTAINER/data /var/delphix zfs defaults,x-systemd.before=zfs-import-cache.service 0 0
 		rpool/ROOT/$CONTAINER/log  /var/log     zfs defaults,x-systemd.before=zfs-import-cache.service 0 0
 		rpool/crashdump            /var/crash   zfs defaults,x-systemd.before=zfs-import-cache.service,x-systemd.before=kdump-tools.service 0 0
